//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.ResourceFiles.ControlBox {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Office2007ControlBoxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Office2007ControlBoxResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krypton.Toolkit.ResourceFiles.ControlBox.Office2007ControlBoxResources", typeof(Office2007ControlBoxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackCloseActive {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackCloseActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackCloseDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackCloseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackCloseNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackCloseNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackClosePressed {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackClosePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackMaximiseActive {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackMaximiseActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackMaximiseDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackMaximiseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackMaximiseNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackMaximiseNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackMaximisePressed {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackMaximisePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackMinimiseActive {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackMinimiseActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackMinimiseDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackMinimiseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackMinimiseNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackMinimiseNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackMinimisePessed {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackMinimisePessed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackRestoreActive {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackRestoreActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackRestoreDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackRestoreDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackRestoreNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackRestoreNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlackRestorePressed {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlackRestorePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueCloseActive {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueCloseActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueCloseDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueCloseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueCloseNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueCloseNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueClosePressed {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueClosePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueMaximiseActive {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueMaximiseActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueMaximiseDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueMaximiseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueMaximiseNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueMaximiseNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueMaximisePressed {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueMaximisePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueMinimiseActive {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueMinimiseActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueMinimiseDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueMinimiseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueMinimiseNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueMinimiseNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueMinimisePessed {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueMinimisePessed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueRestoreActive {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueRestoreActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueRestoreDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueRestoreDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueRestoreNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueRestoreNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxBlueRestorePressed {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxBlueRestorePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverCloseActive {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverCloseActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverCloseDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverCloseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverCloseNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverCloseNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverClosePressed {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverClosePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverMaximiseActive {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverMaximiseActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverMaximiseDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverMaximiseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverMaximiseNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverMaximiseNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverMaximisePressed {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverMaximisePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverMinimiseActive {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverMinimiseActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverMinimiseDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverMinimiseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverMinimiseNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverMinimiseNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverMinimisePessed {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverMinimisePessed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverRestoreActive {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverRestoreActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverRestoreDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverRestoreDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverRestoreNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverRestoreNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007ControlBoxSilverRestorePressed {
            get {
                object obj = ResourceManager.GetObject("Office2007ControlBoxSilverRestorePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007HelpIconDisabled {
            get {
                object obj = ResourceManager.GetObject("Office2007HelpIconDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007HelpIconDisabledV2 {
            get {
                object obj = ResourceManager.GetObject("Office2007HelpIconDisabledV2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007HelpIconHover {
            get {
                object obj = ResourceManager.GetObject("Office2007HelpIconHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007HelpIconNormal {
            get {
                object obj = ResourceManager.GetObject("Office2007HelpIconNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Office2007HelpIconPressed {
            get {
                object obj = ResourceManager.GetObject("Office2007HelpIconPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
