//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Outlook.Grid.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en_Neutral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en_Neutral() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krypton.Toolkit.Suite.Extended.Outlook.Grid.Resources.Language.Strings.en-Neutral" +
                            "", typeof(Strings_en_Neutral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 After next month 的本地化字符串。
        /// </summary>
        internal static string AFTERNEXTMONTH {
            get {
                return ResourceManager.GetString("AFTERNEXTMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alphabetic 的本地化字符串。
        /// </summary>
        internal static string AlphabeticGroupText {
            get {
                return ResourceManager.GetString("AlphabeticGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Bars 的本地化字符串。
        /// </summary>
        internal static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before previous month 的本地化字符串。
        /// </summary>
        internal static string BEFOREPREVIOUSMONTH {
            get {
                return ResourceManager.GetString("BEFOREPREVIOUSMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Best fit 的本地化字符串。
        /// </summary>
        internal static string BESTFIT {
            get {
                return ResourceManager.GetString("BESTFIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Best fit (all columns) 的本地化字符串。
        /// </summary>
        internal static string BESTFITALL {
            get {
                return ResourceManager.GetString("BESTFITALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear grouping 的本地化字符串。
        /// </summary>
        internal static string CLEARGROUPING {
            get {
                return ResourceManager.GetString("CLEARGROUPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear rules... 的本地化字符串。
        /// </summary>
        internal static string ClearRules {
            get {
                return ResourceManager.GetString("ClearRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear sorting 的本地化字符串。
        /// </summary>
        internal static string CLEARSORTING {
            get {
                return ResourceManager.GetString("CLEARSORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse 的本地化字符串。
        /// </summary>
        internal static string COLLAPSE {
            get {
                return ResourceManager.GetString("COLLAPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Columns 的本地化字符串。
        /// </summary>
        internal static string COLUMNS {
            get {
                return ResourceManager.GetString("COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditional formatting 的本地化字符串。
        /// </summary>
        internal static string CONDITIONALFORMATTING {
            get {
                return ResourceManager.GetString("CONDITIONALFORMATTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom... 的本地化字符串。
        /// </summary>
        internal static string CustomThreeDots {
            get {
                return ResourceManager.GetString("CustomThreeDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        internal static string DateGroupText {
            get {
                return ResourceManager.GetString("DateGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a column header here to group by that column 的本地化字符串。
        /// </summary>
        internal static string DRAGCOLUMNTOGROUP {
            get {
                return ResourceManager.GetString("DRAGCOLUMNTOGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Earlier during this month 的本地化字符串。
        /// </summary>
        internal static string EARLIERDURINGTHISMONTH {
            get {
                return ResourceManager.GetString("EARLIERDURINGTHISMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Earlier this year 的本地化字符串。
        /// </summary>
        internal static string EARLIERTHISYEAR {
            get {
                return ResourceManager.GetString("EARLIERTHISYEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand 的本地化字符串。
        /// </summary>
        internal static string EXPAND {
            get {
                return ResourceManager.GetString("EXPAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish 的本地化字符串。
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full collapse 的本地化字符串。
        /// </summary>
        internal static string FULLCOLLAPSE {
            get {
                return ResourceManager.GetString("FULLCOLLAPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full expand 的本地化字符串。
        /// </summary>
        internal static string FULLEXPAND {
            get {
                return ResourceManager.GetString("FULLEXPAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gradient Fill 的本地化字符串。
        /// </summary>
        internal static string GradientFill {
            get {
                return ResourceManager.GetString("GradientFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group by this column 的本地化字符串。
        /// </summary>
        internal static string GROUP {
            get {
                return ResourceManager.GetString("GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group interval 的本地化字符串。
        /// </summary>
        internal static string GROUPINTERVAL {
            get {
                return ResourceManager.GetString("GROUPINTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide GroupBox 的本地化字符串。
        /// </summary>
        internal static string HIDEGROUPBOX {
            get {
                return ResourceManager.GetString("HIDEGROUPBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In three weeks 的本地化字符串。
        /// </summary>
        internal static string INTHREEWEEKS {
            get {
                return ResourceManager.GetString("INTHREEWEEKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In two weeks 的本地化字符串。
        /// </summary>
        internal static string INTWOWEEKS {
            get {
                return ResourceManager.GetString("INTWOWEEKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Later during this month 的本地化字符串。
        /// </summary>
        internal static string LATERDURINGTHISMONTH {
            get {
                return ResourceManager.GetString("LATERDURINGTHISMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next month 的本地化字符串。
        /// </summary>
        internal static string NEXTMONTH {
            get {
                return ResourceManager.GetString("NEXTMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Week 的本地化字符串。
        /// </summary>
        internal static string NEXTWEEK {
            get {
                return ResourceManager.GetString("NEXTWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No date 的本地化字符串。
        /// </summary>
        internal static string NODATE {
            get {
                return ResourceManager.GetString("NODATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Older 的本地化字符串。
        /// </summary>
        internal static string OLDER {
            get {
                return ResourceManager.GetString("OLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 item 的本地化字符串。
        /// </summary>
        internal static string OneItem {
            get {
                return ResourceManager.GetString("OneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom... 的本地化字符串。
        /// </summary>
        internal static string PaletteCustom {
            get {
                return ResourceManager.GetString("PaletteCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom palettes 的本地化字符串。
        /// </summary>
        internal static string PaletteCustomHeading {
            get {
                return ResourceManager.GetString("PaletteCustomHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous month 的本地化字符串。
        /// </summary>
        internal static string PREVIOUSMONTH {
            get {
                return ResourceManager.GetString("PREVIOUSMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous week 的本地化字符串。
        /// </summary>
        internal static string PREVIOUSWEEK {
            get {
                return ResourceManager.GetString("PREVIOUSWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous year 的本地化字符串。
        /// </summary>
        internal static string PREVIOUSYEAR {
            get {
                return ResourceManager.GetString("PREVIOUSYEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Q1 的本地化字符串。
        /// </summary>
        internal static string Q1 {
            get {
                return ResourceManager.GetString("Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Q2 的本地化字符串。
        /// </summary>
        internal static string Q2 {
            get {
                return ResourceManager.GetString("Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Q3 的本地化字符串。
        /// </summary>
        internal static string Q3 {
            get {
                return ResourceManager.GetString("Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Q4 的本地化字符串。
        /// </summary>
        internal static string Q4 {
            get {
                return ResourceManager.GetString("Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quarter 的本地化字符串。
        /// </summary>
        internal static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show GroupBox 的本地化字符串。
        /// </summary>
        internal static string SHOWGROUPBOX {
            get {
                return ResourceManager.GetString("SHOWGROUPBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smart 的本地化字符串。
        /// </summary>
        internal static string Smart {
            get {
                return ResourceManager.GetString("Smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solid Fill 的本地化字符串。
        /// </summary>
        internal static string SolidFill {
            get {
                return ResourceManager.GetString("SolidFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort ascending 的本地化字符串。
        /// </summary>
        internal static string SORTASCENDING {
            get {
                return ResourceManager.GetString("SORTASCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort by summary count 的本地化字符串。
        /// </summary>
        internal static string SORTBYSUMMARYCOUNT {
            get {
                return ResourceManager.GetString("SORTBYSUMMARYCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort descending 的本地化字符串。
        /// </summary>
        internal static string SORTDESCENDING {
            get {
                return ResourceManager.GetString("SORTDESCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Three Color Scale 的本地化字符串。
        /// </summary>
        internal static string ThreeColorsRange {
            get {
                return ResourceManager.GetString("ThreeColorsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Three weeks ago 的本地化字符串。
        /// </summary>
        internal static string THREEWEEKSAGO {
            get {
                return ResourceManager.GetString("THREEWEEKSAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string TODAY {
            get {
                return ResourceManager.GetString("TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tomorrow 的本地化字符串。
        /// </summary>
        internal static string TOMORROW {
            get {
                return ResourceManager.GetString("TOMORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two Color Scale 的本地化字符串。
        /// </summary>
        internal static string TwoColorsRange {
            get {
                return ResourceManager.GetString("TwoColorsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two weeks ago 的本地化字符串。
        /// </summary>
        internal static string TWOWEEKSAGO {
            get {
                return ResourceManager.GetString("TWOWEEKSAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ungroup 的本地化字符串。
        /// </summary>
        internal static string UNGROUP {
            get {
                return ResourceManager.GetString("UNGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  items 的本地化字符串。
        /// </summary>
        internal static string XXXItems {
            get {
                return ResourceManager.GetString("XXXItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year 的本地化字符串。
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year 的本地化字符串。
        /// </summary>
        internal static string YearGroupText {
            get {
                return ResourceManager.GetString("YearGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yesterday 的本地化字符串。
        /// </summary>
        internal static string YESTERDAY {
            get {
                return ResourceManager.GetString("YESTERDAY", resourceCulture);
            }
        }
    }
}
